apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-rs
  namespace: mongo
spec:
  serviceName: mongo-rs
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongod
          image: mongo:8.0
          command: ["mongod", "--config", "/etc/mongod.conf"]
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
            - name: keyfile
              mountPath: /data/keyfile
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mongo-config
        - name: keyfile
          secret:
            secretName: mongo-keyfile
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path       # 你之前已经有 local-path，就用它
        resources:
          requests:
            storage: 10Gi