apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        clusterName: es-cluster
        nodeGroup: "master"

        # 3 副本
        replicas: 3

        # 角色：master+data+ingest（小集群够用）
        roles:
          - master
          - data
          - ingest

        # 关键：PVC 模板 + storageClassName
        volumeClaimTemplate:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

        esJavaOpts: "-Xms1g -Xmx1g"

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"

        service:
          type: ClusterIP
          port: 9200
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true