apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    # 建议固定一个版本号，比如 8.5.1、8.12.x 等，你可以自己改：
    targetRevision: 8.5.1
    helm:
      values: |
        clusterName: es-cluster

        # 单 nodeSet，3 副本，全是 data+master（小集群够用）
        nodeSets:
          - name: default
            count: 3
            config:
              node.roles: ["master", "data", "ingest"]
              node.store.allow_mmap: false
            volumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
              storageClassName: local-path   # <<<<<<<< ★★ 关键
              # 如果你有自己的 StorageClass 可以写这里
              # storageClassName: gp3

        esJavaOpts: "-Xms1g -Xmx1g"

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"

        # 对内访问方式：ClusterIP
        service:
          type: ClusterIP
          port: 9200
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true