apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel          # 要和上面的 Service 名一致
  replicas: 3
  selector:
    matchLabels:
      app: redis
      role: sentinel
  template:
    metadata:
      labels:
        app: redis
        role: sentinel
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: sentinel
          image: redis:7
          command:
            - "redis-sentinel"
            - "/config/sentinel.conf"
          ports:
            - containerPort: 26379
          volumeMounts:
            - name: redis-conf       # 配置文件（来自 ConfigMap）
              mountPath: /config
            - name: data             # 小磁盘
              mountPath: /data
      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
            items:
              - key: sentinel.conf
                path: sentinel.conf