apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-rs
  namespace: mongo
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path     # 或者你的 ebs-gp3 / 其他 SC 名称
        resources:
          requests:
            storage: 20Gi                # 必须要有这个